contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #marsq channel"
    url: https://nfcore.slack.com/channels/marsq
    about: Discussion about the nf-core/marsq pipeline
